# Thymeleaf is default view template.
#jdbc url => jdbc:h2:tcp://localhost/~/test


#h2 Database
spring:
  datasource:
    #url: jdbc:h2:tcp://localhost/~/test  #kyumin
    url: jdbc:h2:tcp://localhost/~/test2 #hncis
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

# show sql as a log (by jpa,hibernate)
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
